name: "Android App Tests"

on:

  workflow_call:
    inputs:
      app_workspace:
        description: "App workspace path"
        required: true
        default: "./"
        type: string

jobs:

#  android-instrumented-tests:
#    name: "Instrumented Tests"
#    timeout-minutes: 30
#    runs-on: macos-latest
#    strategy:
#      matrix:
#        api-level: [34]
#        target: [google_apis]
#        arch: [arm64-v8a]
#    steps:
#      - name: "Checkout Branch"
#        uses: actions/checkout@v5
#        with:
#          submodules: recursive
#      - name: "Install JDK 21"
#        uses: actions/setup-java@v5
#        with:
#          distribution: "zulu"
#          java-version: "21"
#          cache: "gradle"
#      - name: "Run Instrumented Tests"
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          working-directory: ${{ inputs.app_workspace }}
#          api-level: ${{ matrix.api-level }}
#          target: ${{ matrix.target }}
#          arch: ${{ matrix.arch }}
#          avd-name: "avd-${{ matrix.api-level }}"
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: true
#          script: ./gradlew cAT
#      - name: "Archive Instrumented Tests Results"
#        uses: actions/upload-artifact@v3
#        if: ${{ always() }}
#        with:
#          name: "instrumented-tests-results-${{ matrix.api-level }}"
#          path: ./**/build/reports/androidTests/connected/**

  android-unit-tests:
    name: "Android App Unit Tests"
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout"
          uses: actions/checkout@v5
        - name: "Install JDK 21"
          uses: actions/setup-java@v5
          with:
            distribution: "zulu"
            java-version: "21"
            cache: "gradle"
        - name: "Run Unit Tests"
          working-directory: ${{ inputs.app_workspace }}
          run: ./gradlew test
        - name: "Archive App Unit Tests Report"
          uses: actions/upload-artifact@v4
          if: ${{ always() }}
          with:
            name: "app-unit-tests-results"
            path: ./**/build/reports/**
            overwrite: true

  android-lint:
    name: "Android App Lint Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Install JDK 21"
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"
      - name: "Run Lint Checks"
        working-directory: ${{ inputs.app_workspace }}
        run: ./gradlew lint
      - name: "Archive App Lint Test Results"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: "app-lint-results"
          path: ./**/build/reports/**
          overwrite: true

  android-kotlin-lint:
    name: "Android App Kotlin Lint Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Install JDK 21"
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"
      - name: "Run Kotlin Lint Checks"
        working-directory: ${{ inputs.app_workspace }}
        run: ./gradlew ktlintCheck
      - name: "Archive App Lint Test Results"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: "app-kotlin-lint-results"
          path: ./**/build/reports/**
          overwrite: true
