name: "Clikt App Tests"

on:

  workflow_call:
    inputs:
      app_workspace:
        description: "App workspace path"
        required: true
        default: "./"
        type: string

jobs:

  clikt-unit-tests:
    name: "Clikt Unit Tests"
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout"
          uses: actions/checkout@v4
        - name: "Install JDK 21"
          uses: actions/setup-java@v5
          with:
            distribution: "zulu"
            java-version: "21"
            cache: "gradle"
        - name: "Run Unit Tests"
          working-directory: ${{ inputs.app_workspace }}
          run: ./gradlew test
        - name: "Archive Clikt Unit Tests Report"
          uses: actions/upload-artifact@v4
          if: ${{ always() }}
          with:
            name: "clikt-unit-tests-results"
            path: ./**/build/reports/**
            overwrite: true

  # clikt-lint:
  #   name: "Clikt Lint Checks"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v4
  #     - name: "Install JDK 21"
  #       uses: actions/setup-java@v5
  #       with:
  #         distribution: "zulu"
  #         java-version: "21"
  #         cache: "gradle"
  #     - name: "Run Lint Checks"
  #       working-directory: ${{ inputs.app_workspace }}
  #       run: ./gradlew lint
  #     - name: "Archive Lint Test Results"
  #       uses: actions/upload-artifact@v4
  #       if: ${{ always() }}
  #       with:
  #         name: "lint-results"
  #         path: ./**/build/reports/**

  clikt-kotlin-lint:
    name: "Clikt Kotlin Lint Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install JDK 21"
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"
      - name: "Run Kotlin Lint Checks"
        working-directory: ${{ inputs.app_workspace }}
        run: ./gradlew ktlintCheck
      - name: "Archive Clikt Lint Test Results"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: "clikt-kotlin-lint-results"
          path: ./**/build/reports/**
          overwrite: true
